on:
  push:
    branches:
      - create_action
  # create:
  #   tags:
  #     - v*
name: Build framework
jobs:
  static:
    name: Build static
    runs-on: macOS-latest
    needs: create_dirs
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          mkdir -p frameworks/static
          cd ios_sdk_dev
          xcodebuild -target AdjustStatic -configuration Release clean build
  tvOS:
    name: Build tvOS SDK
    runs-on: macOS-latest
    needs: create_dirs
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Universal tvOS SDK
        run: |
          mkdir -p frameworks/static_tvos
          cd ios_sdk_dev
          xcodebuild -configuration Release -target AdjustSdkTv -arch x86_64 -sdk appletvsimulator clean build
          xcodebuild -configuration Release -target AdjustSdkTv -arch arm64 -sdk appletvos build
          cp -Rv build/Release-appletvos/AdjustSdkTv.framework frameworks/static_tvos
          lipo -create -output frameworks/static_tvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvsimulator/AdjustSdkTv.framework/AdjustSdkTv

